Travis update

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,71 +6,95 @@ cache:
   directories:
   - depends/built
   - depends/sdk-sources
-  - $HOME/.ccache
+  - "$HOME/.ccache"
 git:
   depth: false
 env:
   global:
-    - MAKEJOBS=-j4
-    - RUN_TESTS=false
-    - CHECK_DOC=0
-    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
-    - CCACHE_SIZE=100M
-    - CCACHE_TEMPDIR=/tmp/.ccache-temp
-    - CCACHE_COMPRESS=1
-    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
-    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
-    - PYTHON_DEBUG=1
-    - WINEDEBUG=fixme-all
+  - MAKEJOBS=-j4
+  - RUN_TESTS=false
+  - CHECK_DOC=0
+  - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
+  - CCACHE_SIZE=100M
+  - CCACHE_TEMPDIR=/tmp/.ccache-temp
+  - CCACHE_COMPRESS=1
+  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
+  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
+  - PYTHON_DEBUG=1
+  - WINEDEBUG=fixme-all
   matrix:
-# ARM
-    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1" CHECK_DOC=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
-# Win32
-    - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 python3-dev python3-pip nsis g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports" 
-# 32-bit + dash
-    - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-pip python3-dev python3-zmq" DEP_OPTS="NO_QT=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZQM=true
-# Win64
-    - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 python3-dev python3-pip nsis g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports" 
-# bitcoind
-    - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq python3-dev python3-pip" DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER" PYZMQ=true
-# No wallet
-#    - HOST=x86_64-unknown-linux-gnu PACKAGES="python3 python3-dev python3-pip" DEP_OPTS="NO_WALLET=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports" 
-# Cross-Mac
-    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --enable-werror --enable-sse2" OSX_SDK=10.11 GOAL="deploy"
-
+  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1"
+    CHECK_DOC=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
+  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3
+    python3-dev python3-pip nsis g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=false GOAL="install"
+    BITCOIN_CONFIG="--enable-reduce-exports"
+  - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-pip python3-dev python3-zmq"
+    DEP_OPTS="NO_QT=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq
+    --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
+    USE_SHELL="/bin/dash" PYZQM=true
+  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3
+    python3-dev python3-pip nsis g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=false
+    GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
+  - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq python3-dev python3-pip"
+    DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq
+    --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER"
+    PYZMQ=true
+  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
+    libz-dev libbz2-dev libtiff-tools python3-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports
+    --enable-werror --enable-sse2" OSX_SDK=10.11 GOAL="deploy"
 before_install:
-    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
+  sed "s|::|:|g")
 install:
-    - if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
-    - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+- if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
+- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
+  fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
+  --no-upgrade -qq $PACKAGES; fi
 before_script:
-    - unset CC; unset CXX
-    - if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
-    - mkdir -p depends/SDKs depends/sdk-sources
-    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
+- unset CC; unset CXX
+- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
+- mkdir -p depends/SDKs depends/sdk-sources
+- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
+  fi
+- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+- make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
 script:
-#    - if [ "$RUN_TESTS" = "true" -a "$TRAVIS_REPO_SLUG" = "CryptoDragonLady/worx" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then while read LINE; do travis_retry gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys $LINE; done < contrib/verify-commits/trusted-keys; fi
-#    - if [ "$RUN_TESTS" = "true" -a "$TRAVIS_REPO_SLUG" = "CryptoDragonLady/worx" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then git fetch --unshallow; fi
-#    - if [ "$RUN_TESTS" = "true" -a "$TRAVIS_REPO_SLUG" = "CryptoDragonLady/worx" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then contrib/verify-commits/verify-commits.sh; fi
-    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
-    - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
-    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-    - BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
-    - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
-    - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
-    - mkdir build && cd build
-    - ../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
-    - make distdir VERSION=$HOST
-    - cd worx-$HOST
-    - ./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
-    - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
-    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
-    - if [ "$RUN_TESTS" = "true" ]; then make $MAKEJOBS check VERBOSE=1; fi
-    - if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
+- export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
+- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
+- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
+  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
+- depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
+- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
+- mkdir build && cd build
+- "../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || (
+  cat config.log && false)"
+- make distdir VERSION=$HOST
+- cd worx-$HOST
+- "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG ||
+  ( cat config.log && false)"
+- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
+  V=1 ; false )
+- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
+- if [ "$RUN_TESTS" = "true" ]; then make $MAKEJOBS check VERBOSE=1; fi
+- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
 after_script:
-    - echo $TRAVIS_COMMIT_RANGE
-    - echo $TRAVIS_COMMIT_LOG
+- echo $TRAVIS_COMMIT_RANGE
+- echo $TRAVIS_COMMIT_LOG
+    before_deploy:
+      # Set up git user name and tag this commit
+      - git config --local cryptodragonlady "cryptodraonlady"
+      - git config --local dragonlady@coinbotvps.com "dragonlady@coinbotvps.com"
+      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
+    deploy:
+      provider: releases
+    api_key:
+      secure: wjeOwJcH9cUdFJ5lPYrSunC7QqekZWIKwA9TA3Egoz48/L4EX4sKWDFJlPXKLeZXKjZurmK8+pE2vmXxYSDCixsi8c6oWFrxxRlArPTRXhHdJeaUeMo4nQORv2vlVJnrI1Mbi9vyow0y9LMYneoi0tFwDa2AIdjGz7+wFGtixVZkV9THAoNxQJN+qr0LaLeGhGK0r2pBhctpGJW5iQ0aQWmaW7CEQHcaEmN1N5VJSxyyin87UO51t3ld/oK06MNpN4xO9zNlrxDScq1a2lf6Q70IqabeNR7to6/WBPataXuWT4wItILH6IiX9utMBC3NxYOuwfu9mp3FU6SeknJpGVdF3/LqQ4wehHmP80ezOaBdSPgwj12FQEnPrfyTO4LxgBnAEUfeZMUXTSG5+JXDdH5jklDn+3/0iZ4MugGF8hebauefwZBNixbAg74gkC+4Xw0QCiXr5ZGK+pwnHowvmcP3yTwrjntuORWPPmLd8XLUxLbCh/YJz+gPCjojqgcRjSl+lnl6gvN5EFzV/sOF7Z7GKFTI2t+X/tLRFtwpatQ675iy4i6fyLvDgRapsKkL3wUJ6IS4EGje9e5bUPR5Uwb8X3kedPeNUEJ0GKT9lvyIk9sWG5dAUCW5ymzWX0QqJBt9VaYkR4LPYduJ5yv9mKxd9I4RrQHdVrerZppIRdk=
+    file: "FILE TO UPLOAD"
+    skip_cleanup: true
+    on:
+      repo: CryptoDragonLady/worx
